#!/bin/bash
# This is a simple build script and will be executed on your CI system if
# available.  Otherwise it will execute while your application is stopped
# before the deploy step.  This script gets executed directly, so it
# could be python, php, ruby, etc.

set -e

# Prepare the runtime
[ -d $OPENSHIFT_RUNTIME_DIR/go ] ||
	curl  http://go.googlecode.com/files/go.go1.linux-amd64.tar.gz |
	tar xzf - -C $OPENSHIFT_RUNTIME_DIR

export GOROOT=$OPENSHIFT_RUNTIME_DIR/go
export GOPATH=$OPENSHIFT_RUNTIME_DIR/build
export PATH=$GOPATH/bin:$GOROOT/bin:$PATH

rm -rf $GOPATH 2>/dev/null
mkdir -p $GOPATH/src
cp -r $OPENSHIFT_REPO_DIR/$OPENSHIFT_GEAR_NAME $GOPATH/src
go get $OPENSHIFT_GEAR_NAME $OPENSHIFT_GEAR_NAME/...
