#!/bin/bash
# The logic to start up your application should be put in this
# script. The application will work only if it binds to
# $OPENSHIFT_INTERNAL_IP:8080

set -e
export GOROOT=$OPENSHIFT_RUNTIME_DIR/go
export GOPATH=$OPENSHIFT_RUNTIME_DIR/build
export PATH=$GOPATH/bin:$GOROOT/bin:$PATH

nohup $OPENSHIFT_GEAR_NAME > $OPENSHIFT_LOG_DIR/$OPENSHIFT_APP_NAME.log 2>&1 </dev/null &
echo $! >$OPENSHIFT_RUN_DIR/$OPENSHIFT_APP_NAME.pid
